# Metatada of the servicec
service: sls-integrador-elian-${self:provider.stage}
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-prune-plugin

# information about the cloud provider and needed technologies
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:resources.Resources.AuctionsTable.Properties.TableName}
    AUTH_KEY: ${file(secret.pem)}
  # To grant access to any created resource, you need specify the roles/permissions
  iamRoleStatements:
    - ${file(resources/dynamo/auctions-table/iam-roles.yml):AuctionsTableIAM}

# place to define props which aren't part of the sls framework core (plugins config for example)
custom:
  bundle:
    bundle: true
    minify: true
    sourcemap: true
    linting: false
# lambda functions of the stack
functions:
  health:
    handler: src/handlers/health.handler
    events:
      - http:
          method: GET
          path: health
          authorizer: authLambda

  createAuction:
    handler: src/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: create-auction
          cors: true

  getAuctions:
    handler: src/handlers/get-auctions.handler
    events:
      - http:
          method: GET
          path: auctions

  getAuctionById:
    handler: src/handlers/get-auction-by-id.handler
    events:
      - http:
          method: GET
          path: auction/{id}

  placeBid:
    handler: src/handlers/place-bid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true

  processAuction:
    handler: src/handlers/process-auction.handler
    # REVIEW Commented 4 now
    # events:
    #   - schedule:
    #       name: process_auction
    #       rate: rate(1 minute)

  authLambda:
    handler: src/auth/authorizer.handler

# resources needed
resources:
  Resources:
    # Cloudformation Syntax
    AuctionsTable: ${file(resources/dynamo/auctions-table/definition.yml):AuctionsTable}
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
    AuthFailureGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
